---
all:
  children:

    CV_SERVERS:
      hosts:
        lab_cv_instance:
          ansible_host: "{{ lookup('ansible.builtin.env', 'CVURL', default='www.cv-staging.corp.arista.io') }}"

    AVD_FABRIC:
      children:

        AVD_FABRIC_SPINES:
          vars:
            type: spine
          hosts:
            S01:
              ansible_host: 10.0.1.1
            S02:
              ansible_host: 10.0.1.2

        AVD_FABRIC_LEAFS:
          vars:
            type: l3leaf
          children:
            pod0:
              hosts:
                L01:
                  ansible_host: 10.0.2.1
                L02:
                  ansible_host: 10.0.2.2
            pod1:
              hosts:
                L03:
                  ansible_host: 10.0.2.3
                L04:
                  ansible_host: 10.0.2.4

    AVD_FABRIC_ENDPOINTS:
      children:
        AVD_FABRIC_LEAFS:

    AVD_FABRIC_TENANTS:
      children:
        AVD_FABRIC_LEAFS:
