---
fabric_name: AVD_FABRIC

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65100
    loopback_ipv4_pool: 192.0.255.0/24
  nodes:
    - name: S01
      id: 1
      mgmt_ip: 192.168.0.11/24
    - name: S02
      id: 2
      mgmt_ip: 192.168.0.12/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.0.254.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.253.0/24
    uplink_interfaces: ['Ethernet21', 'Ethernet22', 'Ethernet23', 'Ethernet24']
    uplink_switches: ['S01', 'S02', 'S03', 'S04']
    uplink_ipv4_pool: 172.30.255.0/24
    mlag_interfaces: ['Ethernet31', 'Ethernet32']
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: pod0
      bgp_as: 65101
      nodes:
        - name: L01
          id: 1
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: ['Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1']
        - name: L02
          id: 2
          mgmt_ip: 192.168.0.102/24
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2']

p2p_uplinks_mtu: 9214
