---
all:
  children:

    CV_SERVERS:
      hosts:
        lab_cv_instance:
          ansible_host: "{{ lookup('ansible.builtin.env', 'CVURL', default='www.cv-staging.corp.arista.io') }}"

    AVD_FABRIC:
      children:

        AVD_FABRIC_SPINES:
          vars:
            type: spine
          hosts:
            S01:
              ansible_host: 192.168.0.11
            S02:
              ansible_host: 192.168.0.12

        AVD_FABRIC_LEAFS:
          vars:
            type: l3leaf
          children:
            pod0:
              hosts:
                L01:
                  ansible_host: 192.168.0.101
                L02:
                  ansible_host: 192.168.0.102

    AVD_FABRIC_ENDPOINTS:
      children:
        AVD_FABRIC_LEAFS:
        AVD_FABRIC_L2LEAFS:

    AVD_FABRIC_TENANTS:
      children:
        AVD_FABRIC_LEAFS:
        AVD_FABRIC_L2LEAFS: