---
name: build container for {{ cookiecutter.demo_name }}

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/{{ cookiecutter.demo_name }}.yml
      - .github/workflows/container-build-child-workflow.yml
      - containers/{{ cookiecutter.demo_name }}
  workflow_dispatch:
    branches: [main]

jobs:
  build-demo-container:
    uses: ./.github/workflows/container-build-child-workflow.yml
    with:
      container_name: {{ cookiecutter.demo_name }}
      from_image: ghcr.io/aristanetworks/avd/universal
      from_variant: python3.11-avd-v4.6.0
      username: avd
      clab_version: "0.52.0"
      ceos_lab_version: 4.30.3M
