---
name: build container for avd-cvaas-evpn-aa

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/avd-cvaas-evpn-aa.yml
      - .github/workflows/container-build-child-workflow.yml
      - containers/avd-cvaas-evpn-aa
  workflow_dispatch:
    branches: [main]

jobs:
  build-demo-container:
    uses: ./.github/workflows/container-build-child-workflow.yml
    with:
      container_name: avd-cvaas-evpn-aa
      from_image: ghcr.io/aristanetworks/avd/universal
      from_variant: python3.11-avd-v4.6.0
      username: avd
      clab_version: "0.52.0"
      ceos_lab_version: 4.30.3M
