---
name: build container for AVD Extended Workshop, Part 1

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/avd-avd-extended-workshop--part-1.yml
      - .github/workflows/container-build-child-workflow.yml
      - containers/avd-avd-extended-workshop--part-1
  workflow_dispatch:
    branches: [main]

jobs:
  build-demo-container:
    uses: ./.github/workflows/container-build-child-workflow.yml
    with:
      container_name: "avd"
      image_tags: "avd-extended-workshop--part-1"
      from_image: "ghcr.io/aristanetworks/avd/universal"
      from_variant: "python3.11-avd-v4.7.1"
      username: "avd"
      clab_version: "0.54.2"
      ceos_lab_version: "4.30.6M"
      git_init: True
