---
env:
  DEMO_NAME: avd-cvaas-evpn-aa

name: build container for ${DEMO_NAME}

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/${DEMO_NAME}.yml
      - .github/workflows/container-build-child-workflow.yml
      - containers/${DEMO_NAME}
  workflow_dispatch:
    branches: [main]

jobs:
  build-demo-container:
    uses: ./.github/workflows/container-build-child-workflow.yml
    with:
      container_name: ${DEMO_NAME}
      from_image: ghcr.io/aristanetworks/avd/universal
      from_variant: python3.11-avd-v4.6.0
      username: avd
      clab_version: "0.52.0"
      ceos_lab_version: 4.30.3M
