---
name: build multiple containers at once

on:
  push:
    branches: [main, demos_init]
    paths:
      - .github/workflows/container-build-parent-workflow.yml
      - .github/workflows/container-build-child-workflow.yml
      - containers/**

jobs:
  build_demo_containers:
    uses: ./.github/workflows/container-build-child-workflow.yml
    strategy:
      matrix:
        container_name: [avd_cvaas_demos, avd_extended_workshop]
        include:
          - container_name: avd_cvaas_demos
            from_image: ghcr.io/aristanetworks/avd/universal
            from_variant: python3.11-avd-v4.6.0
            username: avd
            clab_version: "0.52.0"
            ceos_lab_version: 4.30.3M
          - container_name: avd_extended_workshop
            from_image: ghcr.io/aristanetworks/avd/universal
            from_variant: python3.11-avd-v4.6.0
            username: avd
            clab_version: "0.52.0"
            ceos_lab_version: 4.30.3M

    with:
      container_name: ${{ matrix.container_name }}
      from_image: ${{ matrix.from_image }}
      from_variant: ${{ matrix.from_variant }}
      username: ${{ matrix.username }}
      clab_version: ${{ matrix.clab_version }}
      platform: ${{ matrix.platform }}
      ceos_lab_version: ${{ matrix.ceos_lab_version }}
      # git_init: ${{ matrix.git_init }}
