name: debug
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code ✅
        uses: actions/checkout@v4

      - name: Set variables for Mkdocs Macros ℹ️
        run: |
          echo "---" > docs/assets/data/github.yml
          echo "org_name: ${{ github.repository_owner }}" >> docs/assets/data/github.yml
          echo "repo_name: ${{ github.event.repository.name }}" >> docs/assets/data/github.yml
          echo "repository: ${{ github.repository }}" >> docs/assets/data/github.yml

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gitvars_artifacts
          path: |
            docs/assets/data/github.yml
