---
name: Create tag.gz to download lab for local use

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/gzip-clab-build-containerlab-with-ceos.yml
      - demos/clab-build-containerlab-with-ceos/**
      - .devcontainer/clab-build-containerlab-with-ceos/**
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code ✅
        uses: actions/checkout@v4

      - name: Archive devcontainer and demo inventory
        run: |
          mkdir clab-build-containerlab-with-ceos
          mkdir clab-build-containerlab-with-ceos/.devcontainer
          mkdir clab-build-containerlab-with-ceos/demos
          cp -r .devcontainer/clab-build-containerlab-with-ceos/* clab-build-containerlab-with-ceos/.devcontainer/
          cp -r demos/clab-build-containerlab-with-ceos/ clab-build-containerlab-with-ceos/demos/
          tar -czvf clab-build-containerlab-with-ceos.tar.gz clab-build-containerlab-with-ceos/
      
      - name: Upload artifact 🔼
        id: upload-artifact-step
        uses: actions/upload-pages-artifact@v3
        with:
          name: clab-build-containerlab-with-ceos.tar.gz
          path: clab-build-containerlab-with-ceos.tar.gz

      - name: Show Artifact URL
        run: echo 'Artifact URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-artifact-step.outputs.artifact-id }}''