name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
    paths:
    - slides/**
    - img/**
    - .github/workflows/marp-to-pages.yml
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code ✅
        uses: actions/checkout@v3

      - name: Copy images 🖼️
        run: |
          mkdir build \
          && cp -R img build/img

      - name: Build HTML from Marp 🔨
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args:  --html slides/avd_cvaas.md -o build/avd_cvaas.html
        env:
          MARP_USER: root:root

      - name: Build PDF from marp_slides.md 🔨
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args:  --html --allow-local-files slides/avd_cvaas.md -o build/avd_cvaas.pdf
        env:
          MARP_USER: root:root

      - name: Deploy production 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/