name: marp-and-mkdocs-to-pages
concurrency: marp-and-mkdocs-to-pages
on:
  push:
    branches: [ main ]
    paths:
    - slides/**
    - docs/**
    - mkdocs.yml
    - img/**
    - .github/workflows/publish-pages.yml
permissions:
  contents: write
jobs:
  build-mkdocs:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code ✅
        uses: actions/checkout@v4

      - name: Setup Python3 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build MkDocs Site
        run: |
          pip install mkdocs-material
          mkdocs build

      - name: Build Directories and Copy images 🖼️
        run: |
          mkdir site/slides \
          && mkdir site/pdfs \
          && cp -R img site/slides/img

      - name: upload artifacts
        uses: actions/upload-artifact@v4

  build_marp:
    runs-on: ubuntu-22.04
    needs: build-mkdocs
    strategy:
      matrix:
        slides_to_build:
          - avd_cvaas
    
    steps:

      - name: download artifacts
        uses: actions/download-artifact@v4

      - name: Build HTML from Marp 🔨
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args:  --html slides/${{ matrix.slides_to_convert }}.md -o site/slides/${{ matrix.slides_to_convert }}.html
        env:
          MARP_USER: root:root

      - name: Build PDF from marp_slides.md 🔨
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args:  --html --allow-local-files slides/${{ matrix.slides_to_convert }}.md -o site/pdfs/${{ matrix.slides_to_convert }}.pdf
        env:
          MARP_USER: root:root

      - name: upload artifacts
        uses: actions/upload-artifact@v4

  deploy_site:
    runs-on: ubuntu-22.04
    needs: build_marp

    steps:

      - name: download artifacts
        uses: actions/download-artifact@v4

      - name: Deploy production 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./site/
